### ISSUE TITLE
I think you have a fork of this contract on the lab 

### ISSUE THREAD

**Issue by smasongarrison** [conorlacey/Conor-Contract#1]
Is it ok if I deleted the old fork of your contract?

https://github.com/R-Computing-Lab/Conor-Contract_old

**Comment by conorlacey** [comment]
Yes that is completely fine! I mistakenly did this. I could not delete it because I'm not an "organization member". Apologies for all my recent SPSS mishaps!!

**Comment by smasongarrison** [comment]
lol, no worries! I'll delete it for you :)
